-- =====================================================================
-- نظام التقييمات — طالب علم
-- شغّل الملف ده مرة واحدة في Supabase Dashboard → SQL Editor → Run
-- ده ملف إضافي منفصل عن analytics/supabase-setup.sql وميأثرش عليه ولا
-- على جدول site_events أو بياناته خالص.
--
-- مهم: حط في السطرين اللي فيهم 'غيّر_الباسورد_ده_CHANGE_ME' هنا تحت
-- نفس الباسورد اللي حطيته في supabase-setup.sql بالظبط، عشان تقدر
-- توافق على التقييمات من نفس لوحة الإحصائيات الخاصة بنفس الباسورد.
-- =====================================================================

-- 1) جدول التقييمات
create table if not exists site_reviews (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  name         text not null,
  rating       smallint not null check (rating between 1 and 5),
  comment      text,
  approved     boolean not null default false,
  constraint site_reviews_name_len check (char_length(name) between 1 and 60),
  constraint site_reviews_comment_len check (comment is null or char_length(comment) <= 500)
);

create index if not exists site_reviews_approved_idx on site_reviews (approved, created_at desc);

-- 2) دفاع إضافي: أي تقييم جديد بيتسجل approved=false إجباري، حتى لو حد
--    حاول يبعت approved=true في نفس الطلب من كود الموقع.
create or replace function force_review_unapproved()
returns trigger
language plpgsql
as $$
begin
  new.approved := false;
  return new;
end;
$$;

drop trigger if exists trg_force_review_unapproved on site_reviews;
create trigger trg_force_review_unapproved
  before insert on site_reviews
  for each row execute function force_review_unapproved();

-- 3) تأمين الجدول
alter table site_reviews enable row level security;

-- أي حد يقدر يبعت تقييم جديد (بيدخل مش منشور لحد ما تتم الموافقة عليه)
drop policy if exists "anyone can submit a review" on site_reviews;
create policy "anyone can submit a review"
  on site_reviews for insert
  to anon
  with check (true);

-- أي حد يقدر يشوف بس التقييمات اللي اتوافق عليها
drop policy if exists "anyone can read approved reviews" on site_reviews;
create policy "anyone can read approved reviews"
  on site_reviews for select
  to anon
  using (approved = true);

-- 4) دوال إدارة التقييمات (محمية بنفس نظام الباسورد بتاع الإحصائيات)
create or replace function admin_list_reviews(p_password text)
returns setof site_reviews
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_password is distinct from 'غيّر_الباسورد_ده_CHANGE_ME' then
    raise exception 'unauthorized';
  end if;

  return query select * from site_reviews order by created_at desc;
end;
$$;

create or replace function admin_review_action(p_password text, p_id bigint, p_action text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_password is distinct from 'غيّر_الباسورد_ده_CHANGE_ME' then
    raise exception 'unauthorized';
  end if;

  if p_action = 'approve' then
    update site_reviews set approved = true where id = p_id;
  elsif p_action = 'delete' then
    delete from site_reviews where id = p_id;
  else
    raise exception 'invalid action';
  end if;
end;
$$;

grant execute on function admin_list_reviews(text) to anon;
grant execute on function admin_review_action(text, bigint, text) to anon;
